##
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

language: java

services:
    - docker

jdk:
    - oraclejdk8

env:
    global:
      # DOCKER_USER
      - secure: JYnhV52L6R4K8M99JNtTQyZsLO/oCzbyTHP6NTOpk5Y65QLFcIgCw6vDxSJhUbzQTSWUIbRcMeNnge8iqsW0HNIosccjnJeOZHsqi5EGgJ/K408KeWXIYZ2aGTqLXnvcF66Md/iTm718EthEfVjRcTkrIy47RHLl8K36MarT85OcIyOp1RAWuQiVTsPmG7t9gL1EqbnL4ZMHJTocidsvyo+uGXHuMhJBuMcls9UmQCL9bxBNh3DNZOyrpJbt7I0pwLnsMJOxmuMAjz2nuRJShdnO/SdrJ2M9VfKVNcwNLyEqH8eLqVTMtbq/3EHPlCGsi2dM13s0FCirfJ6xFjDFhw4cu27AxaAUaoe44SSON0TYpiI1VFaqMcgvvHLiQXpI2MsQVb/GzieKzgeyNU9sMQZ7fmEtuZCPYZyhotWM2ahLof+zIJJ9ttmAdbhuSrLxJXH29PnUj/wm9FfBrq+2WyQa6/BYH080ZwK6r+vSMbF7FcuBnsDvqtcHDCthZf61613P/ZD4QPKyBDW7SUO1Rt8HrNZA4GsrRuRfO65uhRVD3+1bY0mibXEyp8nYHBVB8xJXR7u+VkfIi7jUxJQ4vWr9lHeM7dJA+rN4l3wPbXdNo+EV3TFGg/htKF08HIh4IIDgqzNB4SRlTdOvkpYGAT+uPmXrTzdINtizYBWZCPQ=

      # DOCKER_PASSWORD
      - secure: NoGOgDS3+dRjKiiRvY2lPEIyKLQ0WdHfnq4ub7JvxA8v78HRcdNv1WNQDdevU0sgsQGh0Zx8EATR4hr4dtrtYEG2OHLnoQasbrdPqSQFes0kxymA7u6IWx3adIsgLGJTRdqArW2T4gT79leGypE5ducBONZj2m8A8bqGDphMEnGgpsBO7O3qaXEWOHVZebDx27oqMSURnAfBZUI7tNgTPxTua9jbqPfDuGmY0sHyQXr23Xvajkh+mgYRz5Ad9PNJfdL4J0CfqGShgPDuH9A7K38JUD9cvWDdUgBgeKtyF4aG1+6W1kr63Zt3J2ySITskJAic+O8a0Nz4KdOwlgAbDioyJh2CmF0mGoF7ZjZ/pUhzHKF5VWC8r1mW467oz5k6LLVVTYPFkxv45gX5JIfGzJlGvESiSj/1h+5+5JfbG2+MyxbQFnStd9q9n6Yomb6Gb5BTUeghkJ7B6x3WYuymtB7yxxlRxslSl+0CXqdI/G9ZX5lRgiqQuslM0A0M3aMOWW6yCZNvwwKdGLAvkv/Xm4UZcxzeyLslOYjECc6IsXpNnHDwkSiyv3FWF53+ThQTYE2uLAd/+EvBGTpnUep9Z8Eq68Ywldt9Slx1/PC8T+q6pjr+EbkMaN86XGytgniq77lml6jDT7msnxzDJZy+jM9g/1/1GzLMo2r7R7M5880=


notifications:
    email:
        recipients:
            - enquire+travis@brightsparklabs.com
        on_success: change
        on_failure: always

branches:
    only:
        - master

install:
    - ./gradlew buildDockerImages

script:
    - ./gradlew buildDockerImages

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - ./gradlew publishDockerImages
    - docker logout

