##
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

language: java

services:
    - docker

jdk:
    - openjdk11

notifications:
    email:
        recipients:
            - ci.travis@brightsparklabs.com
        on_success: change
        on_failure: always

branches:
    only:
        - master

before_script:
    - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD

script:
    - ./gradlew publishDockerImages

after_script:
    - docker logout
