##
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

language: java

services:
    - docker

jdk:
    - oraclejdk8

env:
    global:
        # DOCKER_USER
        - secure: "JYnhV52L6R4K8M99JNtTQyZsLO/oCzbyTHP6NTOpk5Y65QLFcIgCw6vDxSJhUbzQTSWUIbRcMeNnge8iqsW0HNIosccjnJeOZHsqi5EGgJ/K408KeWXIYZ2aGTqLXnvcF66Md/iTm718EthEfVjRcTkrIy47RHLl8K36MarT85OcIyOp1RAWuQiVTsPmG7t9gL1EqbnL4ZMHJTocidsvyo+uGXHuMhJBuMcls9UmQCL9bxBNh3DNZOyrpJbt7I0pwLnsMJOxmuMAjz2nuRJShdnO/SdrJ2M9VfKVNcwNLyEqH8eLqVTMtbq/3EHPlCGsi2dM13s0FCirfJ6xFjDFhw4cu27AxaAUaoe44SSON0TYpiI1VFaqMcgvvHLiQXpI2MsQVb/GzieKzgeyNU9sMQZ7fmEtuZCPYZyhotWM2ahLof+zIJJ9ttmAdbhuSrLxJXH29PnUj/wm9FfBrq+2WyQa6/BYH080ZwK6r+vSMbF7FcuBnsDvqtcHDCthZf61613P/ZD4QPKyBDW7SUO1Rt8HrNZA4GsrRuRfO65uhRVD3+1bY0mibXEyp8nYHBVB8xJXR7u+VkfIi7jUxJQ4vWr9lHeM7dJA+rN4l3wPbXdNo+EV3TFGg/htKF08HIh4IIDgqzNB4SRlTdOvkpYGAT+uPmXrTzdINtizYBWZCPQ="
        # DOCKER_PASSWORD
        - secure: "YuoJsYvBIhUGk70w6Ayh6Qna5UtMlQpI0POrzDypgoxU228xWR+47QaFOm3K2drQ1M7UMD0BzkTUP1OJ3Q5TP/LNBT66FCQaNJt08RqKR8OgWtBaz+jSPCVQvKZk8uUMPZA5miOeYTOQRpYd53fxK3cmhYi0F55+NoLNYkOl8Uw9iyA/Hl6wlw6TCZsbEOaRBPN4LaUErpfwYv+HtWIxedmotgTC3nfSdeG5erR16HQMXACKMVDPH1GcZmztzFuHAKQUzb9CZXTr00BX/mB+JiMVPcFNt2o3/8F0gyG04vcG6mZt2/HRHwYo+0+0eSOO8LhjyS5MpeF5Zg32NuWiYwunaunOr7xSFU1iwzV/Bgr9egzMb1LbWAVlnwu4HYy7xAysllJNj8KQ69lZUv8MPGaAPLNqQpi7lA+XdOPeEtao9RsTG9D5J9e+lz/2ZkTCKSYuyQAzlS53p43We2Tjsq85MDvfvXcJzD6OXeK6Ft4TwLgxNgS8mLG4OY+nAWQDISwRzrofoaZExJozr4WbG0AAjttddq9rYNrJqKZnLE+5bne/kQIIsBoRH0WQfycSj+hr+OIYIhlQ5GULYxqTHFoZ+RvANlDo4A42nYI1WCFsGSBsJJj93OueibNHBvWxrWbWfaTVJ9vSCQtS9fQzv5YawX7BeY5FP5Opx04nxJk="

notifications:
    email:
        recipients:
            - enquire+travis@brightsparklabs.com
        on_success: change
        on_failure: always

branches:
    only:
        - master

script:
    - ./gradlew buildDockerImages

after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - ./gradlew publishDockerImages
      - docker logout

