##
 # Alpine based Oracle Java 8 JRE image.
 # _____________________________________________________________________________
 #
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

FROM anapsix/alpine-java:8u102b14_server-jre_unlimited
MAINTAINER brightSPARK Labs <enquire@brightsparklabs.com>
LABEL Description="Alpine based Oracle Java 8 JRE image." Vendor="brightSPARK Labs"

