##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Build and publish docker images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # fetch all history for all branches and tags, so that our `make` targets can get tags
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_PUBLIC }}
          password: ${{ secrets.DOCKER_PASSWORD_PUBLIC }}
      - name: Build and publish docker image
        run: ./gradlew publishDockerImages
