name: Build and publish docker images

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_PUBLIC }}
          password: ${{ secrets.DOCKER_PASSWORD_PUBLIC }}
      - name: Build and publish docker image
        run: ./gradlew publishDockerImages
