##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Debug some issues with tagging.

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # fetch all history for all branches and tags, so that our `make` targets can get tags
        with:
          fetch-depth: 0
      - name: Check the describe version.
        run: git describe --dirty
